title = "Matrimonio Lorenzo e Lucia"
baseURL = "https://matrimoniolorenzolucia.it"
tags = [""]
languageCode = "it-IT"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
# disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Questo matrimonio s'ha da fare!"
  author = "Lorenzo Petrozzino"
  description = "Join the celebrations"
  logoBig = "/images/LogoLL_v2.png"
  logoSmall = "/images/LogoLL_v2.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/LogoLL_v2.png"
  email = ""
  googleTagManager = ""
  customCSS = false

  # Social media links in footer
  # twitter = "TomaNistor"
  # linkedin = "tomanistor"
  # github = "tomanistor"
  # facebook = ""

  # Copyright and theme author credit in footer
  copyright = false
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = true
  cacheBustJS = true

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = "https://usebasin.com/f/0eae7044d4c2"

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "IL PROGRAMMA"
  url  = "/#program"
  weight = 1
[[menu.main]]
  name = "I LUOGHI"
  url  = "/#places"
  weight = 2
[[menu.main]]
  name = "I CONTATTI"
  url  = "/#facci_saper"
  weight = 3
[[menu.man]]
  name = "GALLERIA"
  url  = "/#gallery"
  weight = 4